import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import Stripe from 'stripe';

const ENV_FILE = '.env.local';
const PRODUCT_NAME = 'Next.js SaaS Starter';
const PRODUCT_DESCRIPTION = 'Starter subscription generated by stripe build.';
const PRICE_CURRENCY = 'usd';
const PRICE_UNIT_AMOUNT = 1000;
const PRICE_INTERVAL = 'month';

const rootDir = process.cwd();
const envPath = path.join(rootDir, ENV_FILE);
const envValues = {
  ...readEnvFile(path.join(rootDir, '.env')),
  ...readEnvFile(envPath),
};

const existingPriceId = getEnvValue('STRIPE_PRICE_ID');
if (existingPriceId) {
  console.log(`Stripe is already configured with ${existingPriceId}.`);
  process.exit(0);
}

const secretKey = resolveSecretKey();
if (!secretKey) {
  console.log('Skipping Stripe setup: no secret key found in env or Stripe CLI config.');
  console.log('Run `stripe login` or set STRIPE_SECRET_KEY, then retry with `npm run setup:stripe`.');
  process.exit(0);
}
if (secretKey.startsWith('rk_')) {
  throw new Error('Stripe setup requires a secret key such as sk_test_..., not a restricted key.');
}
if (!secretKey.startsWith('sk_')) {
  throw new Error('Stripe setup requires a Stripe secret key such as sk_test_...');
}

const stripe = new Stripe(secretKey);
const product = await getOrCreateProduct(stripe);
const price = await stripe.prices.create(
  {
    currency: PRICE_CURRENCY,
    product: product.id,
    recurring: {
      interval: PRICE_INTERVAL,
    },
    unit_amount: PRICE_UNIT_AMOUNT,
  },
  {
    idempotencyKey: buildIdempotencyKey('price'),
  },
);

writeEnvFile(envPath, {
  STRIPE_SECRET_KEY: secretKey,
  STRIPE_PRODUCT_ID: product.id,
  STRIPE_PRICE_ID: price.id,
});

console.log('Stripe product and price created.');
console.log(`Product: ${product.id}`);
console.log(`Price: ${price.id}`);
console.log(`Updated ${ENV_FILE}.`);

function getEnvValue(key) {
  return process.env[key]?.trim() || envValues[key]?.trim() || '';
}

function resolveSecretKeyFromStripeCli() {
  try {
    const output = execFileSync('stripe', ['config', '--list'], {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return parseTestModeApiKeyFromStripeCliConfig(output);
  } catch {
    const configPath = process.env.STRIPE_CONFIG?.trim() || path.join(os.homedir(), '.config', 'stripe', 'config.toml');
    if (!fs.existsSync(configPath)) {
      return { profileName: '', secretKey: '' };
    }
    return parseTestModeApiKeyFromStripeCliConfig(fs.readFileSync(configPath, 'utf-8'));
  }
}

function parseConfigAssignment(line, key) {
  const match = line.match(new RegExp(`^${key}\\s*=\\s*(?:'([^']*)'|"([^"]*)"|([^\\s]+))`));
  if (!match) {
    return '';
  }
  return (match[1] || match[2] || match[3] || '').trim();
}

function parseTestModeApiKeyFromStripeCliConfig(config) {
  let profileName = 'default';
  for (const line of config.split(/\r?\n/)) {
    const value = parseConfigAssignment(line.trim(), 'project-name');
    if (value) {
      profileName = value;
      break;
    }
  }

  const activeSectionHeaders = new Set([
    `[${profileName}]`,
    `["${profileName}"]`,
    `['${profileName}']`,
  ]);
  let inActiveSection = false;

  for (const line of config.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (/^\[/.test(trimmed)) {
      inActiveSection = activeSectionHeaders.has(trimmed);
      continue;
    }
    if (!inActiveSection) {
      continue;
    }

    const secretKey = parseConfigAssignment(trimmed, 'test_mode_api_key');
    if (secretKey.startsWith('sk_test_') && !secretKey.includes('*')) {
      return { profileName, secretKey };
    }
  }

  return { profileName: '', secretKey: '' };
}

function resolveSecretKey() {
  const existing = getEnvValue('STRIPE_SECRET_KEY') || getEnvValue('STRIPE_API_KEY');
  if (existing) {
    return existing;
  }

  const { profileName, secretKey: cliSecretKey } = resolveSecretKeyFromStripeCli();
  if (cliSecretKey) {
    console.log(`Using Stripe test mode key from CLI profile "${profileName}".`);
    return cliSecretKey;
  }

  return '';
}

async function getOrCreateProduct(stripe) {
  const existingProductId = getEnvValue('STRIPE_PRODUCT_ID');
  if (existingProductId) {
    return await stripe.products.retrieve(existingProductId);
  }

  return await stripe.products.create(
    {
      description: PRODUCT_DESCRIPTION,
      name: PRODUCT_NAME,
    },
    {
      idempotencyKey: buildIdempotencyKey('product'),
    },
  );
}

function buildIdempotencyKey(resource) {
  const packageName = readPackageName();
  const directoryName = path.basename(rootDir);
  const raw = `stripe-build-${packageName}-${directoryName}-${resource}`;
  return raw.replace(/[^a-zA-Z0-9._-]+/g, '-').slice(0, 255);
}

function readPackageName() {
  try {
    const packageJson = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf-8'));
    return typeof packageJson.name === 'string' && packageJson.name.trim()
      ? packageJson.name.trim()
      : 'template';
  } catch {
    return 'template';
  }
}

function readEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const values = {};
  for (const line of fs.readFileSync(filePath, 'utf-8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) {
      continue;
    }
    const key = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1).trim();
    values[key] = unquoteEnvValue(value);
  }
  return values;
}

function unquoteEnvValue(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function writeEnvFile(filePath, updates) {
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';
  const seen = new Set();
  const lines = existing
    .split(/\r?\n/)
    .filter((line, index, allLines) => index < allLines.length - 1 || line !== '')
    .map((line) => {
      const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=/);
      if (!match || !(match[1] in updates)) {
        return line;
      }
      seen.add(match[1]);
      return `${match[1]}=${updates[match[1]]}`;
    });

  for (const [key, value] of Object.entries(updates)) {
    if (!seen.has(key)) {
      lines.push(`${key}=${value}`);
    }
  }

  fs.writeFileSync(filePath, `${lines.join('\n')}\n`, 'utf-8');
}
